name: flutter_pix_pagstar
description: A package by Pagstar to facilitate Pix transactions with QR Code or random key, featuring customizable design.
version: 1.0.3
repository: https://github.com/pagstar/flutter_pix_pagstar

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/success.png
    - assets/error.png
